[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
soldex = "8KSsmmLyR35acaVM9o9EiQgYyV3PFrGKqzYLCcck8qSH"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
